services:
  - type: web
    name: calendar-weather
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: WEATHERAPI_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GOOGLE_TOKEN
        sync: false 